apiVersion: v1
kind: ServiceAccount
metadata:
  name: webk8s
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: webk8s-role
rules:
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get","list","watch"]

  - apiGroups: [""]
    resources: ["pods","services","configmaps","secrets","events"]
    verbs: ["get","list","watch"]

  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get"]

  - apiGroups: ["apps"]
    resources: ["deployments","replicasets","statefulsets","daemonsets"]
    verbs: ["get","list","watch"]

  - apiGroups: ["batch"]
    resources: ["jobs","cronjobs"]
    verbs: ["get","list","watch"]

  - apiGroups: ["metrics.k8s.io"]
    resources: ["pods"]
    verbs: ["get","list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: webk8s-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: webk8s-role
subjects:
  - kind: ServiceAccount
    name: webk8s
    namespace: kube-system
